[package]
name = "domm-pocket-ic-tests"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
description = "Pocket-IC canister test scaffold for Degens of Misery & Mayhem"

[dependencies]
candid = { workspace = true }
canic-testkit = "0.35.5"
domm-client-probe = { path = "../client-probe" }
domm-degens-canister = { path = "../../canisters/degens" }
domm-game = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
